### ISSUE TITLE
Hi, do you have any plan to release your code? 

### ISSUE THREAD

**Issue by eyuansu62** [hugochan/RL-based-Graph2Seq-for-NQG#1]
It will be very nice if can  release your code!!

**Comment by hugochan** [comment]
> It will be very nice if can release your code!!

Hi, thank you for your interest to our work! We are currently preparing the code and planning to release it probably in early Jan. Please stay tuned!

**Comment by jimmy-walker** [comment]
Hi, do you have plan to release your code within Feb 2020? @hugochan 
Appreciate for your work.

**Comment by hugochan** [comment]
> Hi, do you have plan to release your code within Feb 2020? @hugochan
> Appreciate for your work.

Thank you for your interest to our work! We are busy with conference deadlines. But yes, we are planning to release the code within Feb 2020.

**Comment by hugochan** [comment]
Released the code!
