### ISSUE TITLE
need graph constructed code

### ISSUE THREAD

**Issue by ming-maker** [hugochan/RL-based-Graph2Seq-for-NQG#10]
thanks for sharing your code.
by the way,can you share your graph constructed code?
im so intrested how to do it,
it would be so kind to u if reply me

**Comment by hugochan** [comment]
> thanks for sharing your code.
> by the way,can you share your graph constructed code?
> im so intrested how to do it,
> it would be so kind to u if reply me

@ming-maker thanks for your interest to our work! Here is the graph construction script: https://github.com/hugochan/RL-based-Graph2Seq-for-NQG/blob/master/src/annotate_graphs.py.
