### ISSUE TITLE
Transformer2Seq not found

### ISSUE THREAD

**Issue by keerthana1512** [hugochan/RL-based-Graph2Seq-for-NQG#2]
from .models.transformer2seq import Transformer2Seq
ModuleNotFoundError: No module named 'core.models.transformer2seq'

It would really help me if you could look into this. Thank you.

**Comment by hugochan** [comment]
> from .models.transformer2seq import Transformer2Seq
> ModuleNotFoundError: No module named 'core.models.transformer2seq'
> 
> It would really help me if you could look into this. Thank you.

Thank you for your interest to our work! The Transformer2Seq code was actually not used. So you can simple delete this line. I have pushed a new commit to fix this. Please check out the latest code. 

FYI, to use transformer-based seq2seq, please check out this open source implementation: http://opennmt.net/OpenNMT-py/FAQ.html#how-do-i-use-the-transformer-model

**Comment by keerthana1512** [comment]
Okay. Thank you.
