### ISSUE TITLE
How to preprocess data?

### ISSUE THREAD

**Issue by Lambert-hpx** [hugochan/RL-based-Graph2Seq-for-NQG#3]
Excuse me, could you please share the code of preprocessing the data? I'd like to preprocess my own data and my data format is like the 
train.src
train.tgt
test.src
test.tgt
...
Thank you very much!

**Comment by Lambert-hpx** [comment]
<> <> <> Starting Timer [Train] <> <> <>                                                                                              rl_ratio: 0                                                                                                                                                                                                                                                                 >>> Train Epoch: [1 / 100]                                                                                                            Traceback (most recent call last):                                                                                                      File "main.py", line 57, in <module>                                                                                                    main(config)                                                                                                                        File "main.py", line 23, in main                                                                                                        model.train()                                                                                                                       File "/media/Disk/xxx/RL-based-Graph2Seq-for-NQG-master/src/core/model_handler.py", line 126, in train            self._run_epoch(self.train_loader, training=True, rl_ratio=rl_ratio, verbose=self.config['verbose'])                                File "/media/Disk/xxx/RL-based-Graph2Seq-for-NQG-master/src/core/model_handler.py", line 224, in _run_epoch       x_batch = vectorize_input(input_batch, self.config, self.bert_model, training=training, device=self.device)                         File "/media/Disk/xxx/RL-based-Graph2Seq-for-NQG-master/src/core/utils/data_utils.py", line 61, in vectorize_input                                                                                                                                      all_encoder_layers = all_encoder_layers[layer_indexes]                                                                            IndexError: index 16 is out of bounds for dimension 0 with size 12   




By the way, I use your data to run, but this error occured, how to solve it?

**Comment by Lambert-hpx** [comment]
> <> <> <> Starting Timer [Train] <> <> <>
> rl_ratio: 0 >>> Train Epoch: [1 / 100]
> 
> Traceback (most recent call last):
> 
> File "main.py", line 57, in
> main(config)
> File "main.py", line 23, in main model.train()
> File "/media/Disk/xxx/RL-based-Graph2Seq-for-NQG-master/src/core/model_handler.py", line 126, in train
> self._run_epoch(self.train_loader, training=True, rl_ratio=rl_ratio, verbose=self.config['verbose'])
> File "/media/Disk/xxx/RL-based-Graph2Seq-for-NQG-master/src/core/model_handler.py", line 224, in _run_epoch
> x_batch = vectorize_input(input_batch, self.config, self.bert_model, training=training, device=self.device)
> File "/media/Disk/xxx/RL-based-Graph2Seq-for-NQG-master/src/core/utils/data_utils.py", line 61, in vectorize_input all_encoder_layers = all_encoder_layers[layer_indexes]
> 
> IndexError: index 16 is out of bounds for dimension 0 with size 12
> 
> By the way, I use your data to run, but this error occured, how to solve it?

oooooooh, this may result from my bert_model, I use based because of the large is too big and the network is too slow to download

**Comment by hugochan** [comment]
> Excuse me, could you please share the code of preprocessing the data? I'd like to preprocess my own data and my data format is like the
> train.src
> train.tgt
> test.src
> test.tgt
> ...
> Thank you very much!

Thank you for your interest to our work! We actually do not have script for preparing the dataset since we used the datasets released by earlier works. But I guess it will not be too difficult to prepare the data on your own. You might want to check out the format used in our datasets. 

To annotate the dataset with dependency parsing trees, you can use our script [here](https://github.com/hugochan/RL-based-Graph2Seq-for-NQG/blob/master/src/annotate_graphs.py).

**Comment by Lambert-hpx** [comment]
> > Excuse me, could you please share the code of preprocessing the data? I'd like to preprocess my own data and my data format is like the
> > train.src
> > train.tgt
> > test.src
> > test.tgt
> > ...
> > Thank you very much!
> 
> Thank you for your interest to our work! We actually do not have script for preparing the dataset since we used the datasets released by earlier works. But I guess it will not be too difficult to prepare the data on your own. You might want to check out the format used in our datasets.
> 
> To annotate the dataset with dependency parsing trees, you can use our script [here](https://github.com/hugochan/RL-based-Graph2Seq-for-NQG/blob/master/src/annotate_graphs.py).

Thank you for your response! I have done it on my own. Thank you very much!

**Comment by andrei-volkau** [comment]
@Lambert-hpx  could you clarify the preprocessing process, please? 

It is clear that a dependency parsing tree is required. 

It looks like NLTK is used in order to produce toks/POSs. I struggle to understand in which way NERs/positions are produced. Could you please help with that? 


I am sending an example.
```
{
  "text3": "Twins",
  "text1": "twins -lrb- 1988 -rrb- , a comedy with danny devito , also proved successful .",
  "text2": "What's the title of the comedy movie Schwarzenegger starred in with Danny DeVito in 1988?",
  "annotation3": {
    "raw_text": "Twins",
    "toks": "Twins",
    "POSs": "NNS",
    "positions": "0-0-5",
    "NERs": "O"
  },
  "id": "56de8c374396321400ee2a11",
  "annotation2": {
    "raw_text": "What's the title of the comedy movie Schwarzenegger starred in with Danny DeVito in 1988?",
    "toks": "What 's the title of the comedy movie Schwarzenegger starred in with Danny DeVito in 1988 ?",
    "POSs": "WP VBZ DT NN IN DT NN NN NNP VBD IN IN NNP NNP IN CD .",
    "positions": "0-0-4 1-4-6 2-7-10 3-11-16 4-17-19 5-20-23 6-24-30 7-31-36 8-37-51 9-52-59 10-60-62 11-63-67 12-68-73 13-74-80 14-81-83 15-84-88 16-88-89",
    "NERs": "O O O O O O O O PERSON O O O PERSON PERSON O DATE O"
  },
  "annotation1": {
    "raw_text": "twins -lrb- 1988 -rrb- , a comedy with danny devito , also proved successful .",
    "toks": "twins -lrb- 1988 -rrb- , a comedy with danny devito , also proved successful .",
    "POSs": "NNS JJ CD NN , DT NN IN JJ NN , RB VBD JJ .",
    "positions": "0-0-5 1-6-11 2-12-16 3-17-22 4-23-24 5-25-26 6-27-33 7-34-38 8-39-44 9-45-51 10-52-53 11-54-58 12-59-65 13-66-76 14-77-78",
    "NERs": "O O DATE O O O O O O O O O O O O",
    "graph": {
      "g_features": [
        "twins",
        "-lrb-",
        "1988",
        "-rrb-",
        ",",
        "a",
        "comedy",
        "with",
        "danny",
        "devito",
        ",",
        "also",
        "proved",
        "successful",
        "."
      ],
      "g_adj": {
        "0": [
          {
            "node": 1,
            "edge": "punct"
          },
          {
            "node": 2,
            "edge": "appos"
          },
          {
            "node": 3,
            "edge": "punct"
          },
          {
            "node": 4,
            "edge": "punct"
          },
          {
            "node": 6,
            "edge": "appos"
          },
          {
            "node": 10,
            "edge": "punct"
          }
        ],
        "6": [
          {
            "node": 5,
            "edge": "det"
          },
          {
            "node": 7,
            "edge": "prep"
          }
        ],
        "7": [
          {
            "node": 9,
            "edge": "pobj"
          }
        ],
        "9": [
          {
            "node": 8,
            "edge": "amod"
          }
        ],
        "12": [
          {
            "node": 0,
            "edge": "nsubj"
          },
          {
            "node": 11,
            "edge": "advmod"
          },
          {
            "node": 13,
            "edge": "oprd"
          },
          {
            "node": 14,
            "edge": "punct"
          }
        ]
      },
      "num_edges": 14
    }
  }
}
```
