### ISSUE TITLE
`rl_wmd_ratio` not found

### ISSUE THREAD

**Issue by jeremytanjianle** [hugochan/RL-based-Graph2Seq-for-NQG#4]
Hi, I tried to run the exact code in the readme, but encountered this error.

Read the paper, and it's a great work by the way. Thanks for sharing the code.

```
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    main(config)
  File "main.py", line 22, in main
    model = ModelHandler(config)
  File "C:\Users\User\Desktop\G2S_NQG\RL-based-Graph2Seq-for-NQG\src\core\model_handler.py", line 73, in __init__
    self.model = Model(config, train_set)
  File "C:\Users\User\Desktop\G2S_NQG\RL-based-Graph2Seq-for-NQG\src\core\model.py", line 69, in __init__
    if config['rl_wmd_ratio'] > 0:
KeyError: 'rl_wmd_ratio'
```

**Comment by hugochan** [comment]
Hi, thank you for your interest to our work! I just fixed the error. Please feel free to check out the latest code. 

> Hi, I tried to run the exact code in the readme, but encountered this error.
> 
> Read the paper, and it's a great work by the way. Thanks for sharing the code.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 57, in <module>
>     main(config)
>   File "main.py", line 22, in main
>     model = ModelHandler(config)
>   File "C:\Users\User\Desktop\G2S_NQG\RL-based-Graph2Seq-for-NQG\src\core\model_handler.py", line 73, in __init__
>     self.model = Model(config, train_set)
>   File "C:\Users\User\Desktop\G2S_NQG\RL-based-Graph2Seq-for-NQG\src\core\model.py", line 69, in __init__
>     if config['rl_wmd_ratio'] > 0:
> KeyError: 'rl_wmd_ratio'
> ```

Hi, thank you for your interest to our work! I just fixed the error. Please feel free to check out the latest code.

**Comment by jeremytanjianle** [comment]
Thanks, it's running now.
